### ISSUE TITLE
VMWare ESXi login page at https://piotradamczyk.pl/ui/#/login

### ISSUE THREAD

**Issue by sio** [imxeno/imxeno#1]
ESXi login page is exposed at https://piotradamczyk.pl/ui/#/login
![screenshot](https://user-images.githubusercontent.com/334908/135060489-b03a865a-7630-4c4e-bce8-5ff30edce558.png)

Public internet is a nasty place and you really should not expose your hypervisor like that. Malicious actors might get in either via bruteforce or by waiting for a zero-day vulnerability.

**Comment by imxeno** [comment]
Hello @sio!

Thanks for letting me know. I was kinda surprised at first because this domain should no longer point to anything (nowadays I use it just for my personal email). Though, it turns out that it was still pointing to an IP address of an OVH dedicated machine, which is no longer under my control. I removed the A record, but I have no way to contact the current owner of this server. 😞 

Best regards,
Piotr

**Comment by sio** [comment]
Yeah, plenty of misconfigured hosts out there. We can't fix the whole Internet :-)
